/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from 'leva'

export default function Island(props) {

  const { nodes, materials } = useGLTF("/island.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          geometry={nodes.Object_10.geometry}
          material={materials.curve_Pipe}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.island_Connector_CURVE}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.island_Metal_holders}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.machine_MAIN}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials.machine_REACTOR}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.machine_REACTOR_transparent}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials.machine_RENTGEN}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.machine_TELEPORT_flash}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials.machine_TELEPORT_transparent}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.ISLAND_BASE}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.ISLAND_BASE}
        />
        <mesh
          geometry={nodes.Object_22.geometry}
          material={materials.machine_PRINTER}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.machine_PRINTER}
        />
        <mesh
          geometry={nodes.Object_24.geometry}
          material={materials.machine_TELEPORT}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.machine_TELEPORT}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.DROPS_PIPE}
        />
        <mesh
          geometry={nodes.Object_6.geometry}
          material={materials.ISLAND_BASE_SHADOW}
        />
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.base_island_additional_pipes}
        />
        <mesh
          geometry={nodes.Object_8.geometry}
          material={materials["base_island_additional_pipes_BEAM.001"]}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.base_island_additional_pipes_transarent}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/island.glb");
