/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Linkedin(props) {
  const { nodes, materials } = useGLTF("/linkedin.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Object_5001"
        geometry={nodes.Object_5001.geometry}
        material={materials["glossy_putih.001"]}
        position={[0.056, 0.047, 0.06]}
        rotation={[1.581, 0, 0]}
      />
      <mesh
        name="Object_4002"
        geometry={nodes.Object_4002.geometry}
        material={materials.glossy_linkedin}
        position={[0.087, 0.154, -0.277]}
        rotation={[1.581, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/linkedin.glb");

