/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from '@react-three/rapier'

export default function Connect4board({ onClick, ...props }) {

  const { nodes, materials } = useGLTF("/connect4.glb");
  return (
    <group {...props} dispose={null}>
      <RigidBody
        type="fixed"
        colliders="trimesh"
      >
        <mesh
          name="connect4"
          geometry={nodes.connect4.geometry}
          scale={1.013}
        >
          <meshStandardMaterial
            color={[0.5, 0.5, 2]}
            roughness={0.1}
            metalness={1}
          />
        </mesh>
      </RigidBody>
      <RigidBody
        type="fixed"
        colliders="cuboid"
      >
        <mesh
          name="connect4Bottom"
          geometry={nodes.connect4Bottom.geometry}
          position={[0, 0, -3.145]}
        >
          <meshStandardMaterial
            color={[0, 0, 0]}
            roughness={0.1}
            metalness={1}
          />
        </mesh>
      </RigidBody>
      <mesh
        name="connect4Background0"
        geometry={nodes.connect4Background0.geometry}
        position={[-5.39, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
      <mesh
        name="connect4Background1"
        geometry={nodes.connect4Background1.geometry}
        position={[11.389, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
      <mesh
        name="connect4Background2"
        geometry={nodes.connect4Background2.geometry}
        position={[28.168, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
      <mesh
        name="connect4Background3"
        geometry={nodes.connect4Background3.geometry}
        position={[45.179, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
      <mesh
        name="connect4Background4"
        geometry={nodes.connect4Background4.geometry}
        position={[61.958, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
      <mesh
        name="connect4Background5"
        geometry={nodes.connect4Background5.geometry}
        position={[78.737, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
      <mesh
        name="connect4Background6"
        geometry={nodes.connect4Background6.geometry}
        position={[95.282, -5.497, 1.663]}
        scale={[51.916, 37.978, 42.212]}
        onClick={onClick}
      >
        <meshStandardMaterial
          color={[0, 0, 0]}
          roughness={0.1}
          metalness={1}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/connect4.glb");