/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Github(props) {
  const { nodes, materials } = useGLTF("/github.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="github"
        position={[0.516, -31.474, -10.405]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={1.898}
      >
        <group name="GLTF_SceneRootNode001" rotation={[Math.PI / 2, 0, 0]}>
          <group
            name="Curve012_0"
            position={[-0.055, 2.945, 6.336]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={28.364}
          >
            <mesh
              name="Object_4001"
              geometry={nodes.Object_4001.geometry}
              material={materials.glossy_putih}
              position={[0.002, 0, -0.493]}
            />
            <mesh
              name="Object_5"
              geometry={nodes.Object_5.geometry}
              material={materials.github}
              position={[0.002, -0.012, -0.491]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/github.glb");

