/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: skybox3dArchitect (https://sketchfab.com/skybox3dArchitect)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/skybox-orange-sky-626c5de48bb74c94906ecdd72df04c80
Title: Skybox Orange Sky
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Skybox(props) {
  const { nodes, materials } = useGLTF("/skybox.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Object_4"
        geometry={nodes.Object_4.geometry}
        material={materials.Skybox_mat}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/skybox.glb");
