/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Twitter(props) {
  const { nodes, materials } = useGLTF("/twitter.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="twitter"
        rotation={[Math.PI / 2, 0, 0]}
        scale={[242.294, 242.295, 242.295]}
      >
        <mesh
          name="TwitterRoot"
          geometry={nodes.TwitterRoot.geometry}
          material={materials["glossy putih.010"]}
        />
        <mesh
          name="TwitterRoot_1"
          geometry={nodes.TwitterRoot_1.geometry}
          material={materials["glossy twitter"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/twitter.glb");
